#!/bin/bash

set -euox pipefail

function profile_load() {
  # - Clear GOFLAGS in case "-mod=vendor" is set.
  GO111MODULE=on GOFLAGS= go run -v repro.go \
    -pkgdir tools \
    -pkgmax 10 \
    -memprofile mem.prof
  go tool pprof -top -cum -alloc_space mem.prof > $1.top
}

function main() {
  # Use a convenient source of packages.
  if [ ! -d ./tools ]; then
    git clone --depth 1 https://github.com/golang/tools.git
  fi

  # One commit prior to potential regression
  cp go.mod.45dd101d8784 go.mod
  profile_load 45dd101d8784

  # Potential regression commit based on bisect
  cp go.mod.dbeab5af4b8d go.mod
  profile_load dbeab5af4b8d

  # Current newest
  cp go.mod.e31d36578abb go.mod
  profile_load e31d36578abb

  rm go.mod go.sum
}

main
