#!/bin/bash

set -euox pipefail

function profile_load() {
  # - Clear GOFLAGS in case "-mod=vendor" is set.
  GO111MODULE=on GOFLAGS= go run -v repro.go \
    -pkgdir tools \
    -pkgmax 10 \
    -memprofile mem.prof
  go tool pprof -top -cum -alloc_space mem.prof > $1.top
}

function main() {
  # Use a convenient source of packages.
  if [ ! -d ./tools ]; then
    git clone --depth 1 https://github.com/golang/tools.git
  fi

  cd ./tools

  # Just to keep it consistent.
  git checkout 2d16b83

  cd ../

  # One commit prior to potential regression
  cp go.mod.45dd101d878 go.mod
  profile_load 45dd101d87

  # Potential regression commit based on bisect
  cp go.mod.dbeab5af4b8d go.mod
  profile_load dbeab5af4b8d

  # Current newest
  cp go.mod.cf84161cff3f go.mod
  profile_load cf84161cff3f
}

main
